### ISSUE TITLE
Dependency management and requirements

### ISSUE THREAD

**Issue by armantekinalp** [hh-19/PyElasticaVisualizer#1]
Hi @hh-19,

1. I am wondering why `PyElastica` is a dependency for this package? I was thinking adding this package as an optional dependency to the `PyElastica` and install with `PyElastica` examples.
2. Also in `PyElastica` with version release `0.3.0` mid August, we are moving to poetry for managing the dependencies. So do you think we can do the same for `PyElasticaVisualizer` dependencies and use poetry?

**Comment by hh-19** [comment]
Hi @armantekinalp,

Yes you're right for 1), I had PyElastica as a dependency for this package so you could run the examples, but the intended usage of this module will be as an optional dependency for PyElastica so it is unnecessary and circular. I will remove it. 

Sure, I can move dependencies over to poetry. 


In the mean time, do let me know any other comments you might have.  

Thanks
